clc;
close all

figure(1);
subplot(3,4,1)  
plot(time,PsiRref,'k--',time,Psi_R_observer,'k',time,PsiR,'g--')
xlabel('Time [s]')
ylabel('Rotor Flux [Wb]')
title('\Psi_R ref red, \Psi_R est green, \Psi_R true blue')
legend('Reference', 'Estimated', 'True')

subplot(3,4,2)  
plot(time,(180/pi)*Theta_r_observer,'k',time,(180/pi)*unwrap(Psir_angle),'g--')
xlabel('Time [s]')
ylabel('Rotor Flux Angle [Wb]')
title('\Theta_r estimated green, \Theta_r true blue')
legend('Estimated', 'True')

subplot(3,4,3)  
plot(time,w1_hat,'k--',time,w1,'g--')
xlabel('Time [s]')
ylabel('Stator Frequncy [rad/s]')
title('\Omega_1 estimated green, \Omega_1 true blue')
legend('Estimated', 'True')

subplot(3,4,4)  
plot(time,wrref*60/(2*pi),'k--',time,Wr_hat*60/(2*pi),'k',time,Wr*60/(2*pi),'g--')
xlabel('Time [s]')
ylabel('Rotor Speed [RPM]')
title('\Omega_r reference red, \Omega_r estimated green, \Omega_r true blue')
legend('Reference', 'Estimated', 'True')

subplot(3,4,5)  
plot(time,(PsiR - Psi_R_observer),'k')
xlabel('Time [s]')
ylabel('Rotor Flux Magnitude Estimation Error [Wb]')
title('\Psi_R Estimation Error red')
legend('Rotor Flux Magnitude Estimation Error')

subplot(3,4,6)  
plot(time,(180/pi)*(unwrap(Psir_angle)-Theta_r_observer),'k')
xlabel('Time [s]')
ylabel('Rotor Flux Angle Estimation Error [rad]')
title('\Psi_R Angle Estimation Error red')
legend('Rotor Flux Angle Estimation Error')

subplot(3,4,7)  
plot(time,(w1 - w1_hat),'k')
xlabel('Time [s]')
ylabel('Stator Frequency Estimation Error [Wb]')
title('\Omega_1 Estimation Error red')
legend('Stator Frequency Estimation Error')

subplot(3,4,8)  
plot(time,60/(2*pi)*(Wr - Wr_hat),'k')
xlabel('Time [s]')
ylabel('Rotor Speed Estimation Error [RPM]')
title('\Omega_r Estimation Error red')
legend('Rotor Speed Estimation Error')

subplot(3,4,9)  
plot(time,isdref,'k--',time,real(isdq_estimated),'k',time,isd,'g--')
xlabel('Time [s]')
ylabel('i_d [A]')
title('i_d reference red, i_d estimated, i_d true blue')
legend('Reference', 'Estimated', 'True')

subplot(3,4,10)  
plot(time,isqref,'k--',time,imag(isdq_estimated),'k',time,isq,'g--')
xlabel('Time [s]')
ylabel('i_q [A]')
title('i_q reference red, i_q estimated, i_q true blue')
legend('Reference', 'Estimated', 'True')

subplot(3,4,11)  
plot(time,Teref_controller,'k--',time,Te,'g--',time,TL,'b')
xlabel('Time [s]')
ylabel('Torque [Nm]')
title('T_{e:ref} red, T_e red, T_L black')
legend('Reference', 'Electromagnetic', 'Load')